a1.dot: a1.in viz.rb
	ruby viz.rb a1.in > a1.dot
a1.png: a1.dot
	dot -Tpng a1.dot > a1.png
a2.dot: a2.in viz.rb
	ruby viz.rb a2.in > a2.dot
a2.png: a2.dot
	dot -Tpng a2.dot > a2.png
a3.dot: a3.in viz.rb
	ruby viz.rb a3.in > a3.dot
a3.png: a3.dot
	dot -Tpng a3.dot > a3.png
